### ISSUE TITLE
Request method 'POST' not supported

### ISSUE THREAD

**Issue by ericrycuny** [aseduma/Demo#2]
Hi,

after login there's a blank page and the log says

2017-05-07 10:56:39.215  WARN 4236 --- [nio-9060-exec-4] o.s.web.servlet.PageNotFound             : Request method 'POST' not supported

thanks

**Comment by ericrycuny** [comment]
by the way I added in 
**za.co.demo.bean.Party**
`
    @Column(name = "email_address", nullable = false)
    public String getEmailAddress() {
        return emailAddress;
    }
`

**Comment by aseduma** [comment]
Hi Ericrycuny,

Thank you very much for adding that annotation, I forgot to add it.And i'm still working on this project to be fully functional

**Comment by ericrycuny** [comment]
Well done, I think you're doing a terrific job !
keep up the good work :)
